/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['security.js']) {
  _$jscoverage['security.js'] = [];
  _$jscoverage['security.js'][1] = 0;
  _$jscoverage['security.js'][2] = 0;
  _$jscoverage['security.js'][3] = 0;
  _$jscoverage['security.js'][5] = 0;
  _$jscoverage['security.js'][6] = 0;
  _$jscoverage['security.js'][7] = 0;
  _$jscoverage['security.js'][10] = 0;
  _$jscoverage['security.js'][11] = 0;
  _$jscoverage['security.js'][12] = 0;
  _$jscoverage['security.js'][15] = 0;
  _$jscoverage['security.js'][16] = 0;
  _$jscoverage['security.js'][17] = 0;
}
_$jscoverage['security.js'].source = ["\"use strict\";","var crypto = require('crypto');","module.exports = {","  md5: function(data) {","    var shasum = crypto.createHash('md5');","    shasum.update(data);","    return shasum.digest('base64');","  },","  sha1: function(data) {","    var shasum = crypto.createHash('sha1');","    shasum.update(data);","    return shasum.digest('base64');","  },","  sha512: function(data) {","    var shasum = crypto.createHash('sha512');","    shasum.update(data);","    return shasum.digest('base64');","  }","};","","//# sourceMappingURL=security.js.map"];
_$jscoverage['security.js'][1]++;
"use strict";
_$jscoverage['security.js'][2]++;
var crypto = require("crypto");
_$jscoverage['security.js'][3]++;
module.exports = {md5: (function (data) {
  _$jscoverage['security.js'][5]++;
  var shasum = crypto.createHash("md5");
  _$jscoverage['security.js'][6]++;
  shasum.update(data);
  _$jscoverage['security.js'][7]++;
  return shasum.digest("base64");
}), sha1: (function (data) {
  _$jscoverage['security.js'][10]++;
  var shasum = crypto.createHash("sha1");
  _$jscoverage['security.js'][11]++;
  shasum.update(data);
  _$jscoverage['security.js'][12]++;
  return shasum.digest("base64");
}), sha512: (function (data) {
  _$jscoverage['security.js'][15]++;
  var shasum = crypto.createHash("sha512");
  _$jscoverage['security.js'][16]++;
  shasum.update(data);
  _$jscoverage['security.js'][17]++;
  return shasum.digest("base64");
})};
